export const CATEGORY_SCHEMAS = {
  researcher: [
    { name: 'nome', type: 'texto', description: 'Nome completo do pesquisador.' },
    { name: 'categoria', type: 'texto', description: 'Valor fixo: pesquisador.' },
    { name: 'instituicao_atual', type: 'texto', description: 'Instituição e vínculo atual.' },
    { name: 'pais', type: 'texto', description: 'País de atuação principal.' },
    { name: 'cidade_estado', type: 'texto', description: 'Cidade e estado/província, quando localizados.' },
    { name: 'cargo', type: 'texto', description: 'Cargo ou função pública atual.' },
    { name: 'areas_especialidade', type: 'lista', description: 'Áreas de especialidade.' },
    { name: 'linhas_pesquisa', type: 'texto', description: 'Linhas de pesquisa relacionadas ao contexto.' },
    { name: 'publicacoes_relevantes', type: 'lista', description: 'Publicações relevantes, com DOI ou URL.' },
    { name: 'identificadores', type: 'lista', description: 'ORCID, OpenAlex, Google Scholar ou outros identificadores públicos.' },
    { name: 'idiomas', type: 'lista', description: 'Idiomas públicos para contato ou participação.' },
    { name: 'website_oficial', type: 'url', description: 'Página institucional ou profissional pública.' },
    { name: 'contato_publico', type: 'texto', description: 'Contato profissional publicado pela instituição.' },
    { name: 'aderencia_contexto', type: 'texto', description: 'Justificativa da aderência ao contexto informado.' },
    { name: 'evidencias_publicas', type: 'lista', description: 'Fatos que sustentam a recomendação.' },
    { name: 'fontes', type: 'lista', description: 'URLs das fontes consultadas.' },
    { name: 'data_consulta', type: 'data', description: 'Data de cada consulta.' },
    { name: 'confianca', type: 'numero_0_100', description: 'Confiança da coleta, sem inventar precisão.' },
    { name: 'dados_nao_localizados', type: 'lista', description: 'Campos que não foram localizados.' },
  ],
  school: [
    { name: 'nome', type: 'texto', description: 'Nome oficial da instituição.' },
    { name: 'categoria', type: 'texto', description: 'Valor fixo: escola.' },
    { name: 'pais', type: 'texto', description: 'País de atuação.' },
    { name: 'cidade_estado', type: 'texto', description: 'Localização pública.' },
    { name: 'tipo_instituicao', type: 'texto', description: 'Tipo e natureza da instituição.' },
    { name: 'niveis_oferta', type: 'lista', description: 'Níveis e modalidades de EPT ofertados.' },
    { name: 'areas_formacao', type: 'lista', description: 'Áreas de formação.' },
    { name: 'relacao_industria', type: 'texto', description: 'Evidências da relação com indústria e trabalho.' },
    { name: 'escala', type: 'texto', description: 'Alcance, unidades ou público atendido.' },
    { name: 'acreditacoes', type: 'lista', description: 'Acreditações ou reconhecimentos públicos.' },
    { name: 'website_oficial', type: 'url', description: 'Site institucional.' },
    { name: 'contato_publico', type: 'texto', description: 'Contato institucional público.' },
    { name: 'aderencia_contexto', type: 'texto', description: 'Justificativa da aderência.' },
    { name: 'evidencias_publicas', type: 'lista', description: 'Fatos que sustentam a recomendação.' },
    { name: 'fontes', type: 'lista', description: 'URLs das fontes consultadas.' },
    { name: 'data_consulta', type: 'data', description: 'Data de consulta.' },
    { name: 'confianca', type: 'numero_0_100', description: 'Confiança da coleta.' },
    { name: 'dados_nao_localizados', type: 'lista', description: 'Campos ausentes.' },
  ],
  organization: [
    { name: 'nome', type: 'texto', description: 'Nome oficial da organização.' },
    { name: 'categoria', type: 'texto', description: 'Valor fixo: organização.' },
    { name: 'pais', type: 'texto', description: 'País de atuação.' },
    { name: 'cidade_estado', type: 'texto', description: 'Localização pública.' },
    { name: 'natureza_juridica', type: 'texto', description: 'Natureza pública, privada, terceiro setor ou outra.' },
    { name: 'setor', type: 'texto', description: 'Setor de atividade.' },
    { name: 'atuacao', type: 'texto', description: 'Atuação e alcance.' },
    { name: 'programas_relevantes', type: 'lista', description: 'Programas relacionados ao contexto.' },
    { name: 'parcerias_industriais', type: 'lista', description: 'Parcerias ou relação com a indústria.' },
    { name: 'alcance_geografico', type: 'texto', description: 'Alcance territorial.' },
    { name: 'website_oficial', type: 'url', description: 'Site institucional.' },
    { name: 'contato_publico', type: 'texto', description: 'Contato institucional público.' },
    { name: 'aderencia_contexto', type: 'texto', description: 'Justificativa da aderência.' },
    { name: 'evidencias_publicas', type: 'lista', description: 'Fatos que sustentam a recomendação.' },
    { name: 'fontes', type: 'lista', description: 'URLs das fontes consultadas.' },
    { name: 'data_consulta', type: 'data', description: 'Data de consulta.' },
    { name: 'confianca', type: 'numero_0_100', description: 'Confiança da coleta.' },
    { name: 'dados_nao_localizados', type: 'lista', description: 'Campos ausentes.' },
  ],
};

export function generateResearchPrompt({ category, context, purpose, geography, quantity, extraCriteria }) {
  const schema = CATEGORY_SCHEMAS[category] || CATEGORY_SCHEMAS.organization;
  const schemaLines = schema.map((column, index) => (index + 1) + '. ' + column.name + ' (' + column.type + ') — ' + column.description).join('\n');
  const sections = [
    'CONTEXTO DA BUSCA',
    '- Contexto: ' + (context || 'não informado'),
    '- Finalidade: ' + (purpose || 'não informada'),
    '- Geografia: ' + (geography || 'sem preferência'),
    '- Quantidade máxima desejada: ' + (quantity || 'a definir'),
    '- Critérios adicionais: ' + (extraCriteria || 'nenhum além do contexto'),
    '',
    'ESCOPO E CRITÉRIO INSTITUCIONAL',
    'Considere sempre a contribuição potencial para educação profissional de qualidade, desenvolvimento da indústria paulista, inovação, tecnologia, sustentabilidade, desenvolvimento regional e parcerias aplicáveis. Explique quando a conexão for apenas contextual e não direta.',
    '',
    'REGRAS DE EVIDÊNCIA',
    '1. Use somente informações públicas e cite a URL exata de cada fato relevante.',
    '2. Não invente fatos, pessoas, organizações, cargos, números, colunas ou contatos.',
    '3. Quando um dado não for localizado, escreva exatamente “não localizado” no campo correspondente.',
    '4. Separe fatos encontrados de inferências e sinalize conflitos entre fontes.',
    '5. Informe a data de consulta e uma confiança de 0 a 100 acompanhada de justificativa.',
    '',
    'SAÍDA OBRIGATÓRIA',
    'Entregue uma planilha XLSX. Se a ferramenta não conseguir gerar XLSX, entregue CSV UTF-8 com os mesmos nomes, ordem e tipos de colunas. Não crie abas ou colunas extras sem declarar explicitamente que são metadados técnicos fora da tabela principal.',
    '',
    'COLUNAS EXATAS, NESTA ORDEM',
    schemaLines,
    '',
    'Antes da tabela, escreva um resumo curto dos critérios usados, lacunas e limitações. Depois da tabela, liste fontes que falharam, conflitos e próximos passos.',
  ];
  return 'Você é um pesquisador responsável por uma pesquisa pública e rastreável de stakeholders para o SENAI-SP.\n\n' + sections.join('\n');
}
