const countryFlags = {
  'Brasil': '🇧🇷',
  'EUA': '🇺🇸',
  'Alemanha': '🇩🇪',
  'Franca': '🇫🇷',
  'França': '🇫🇷',
  'Reino Unido': '🇬🇧',
  'Japao': '🇯🇵',
  'Japão': '🇯🇵',
  'Coreia do Sul': '🇰🇷',
  'China': '🇨🇳',
  'India': '🇮🇳',
  'Índia': '🇮🇳',
  'Australia': '🇦🇺',
  'Austrália': '🇦🇺',
  'Canada': '🇨🇦',
  'Canadá': '🇨🇦',
  'Italia': '🇮🇹',
  'Itália': '🇮🇹',
  'Singapura': '🇸🇬',
  'Holanda': '🇳🇱',
  'Suica': '🇨🇭',
  'Suíça': '🇨🇭',
  'Mexico': '🇲🇽',
  'México': '🇲🇽',
  'Colombia': '🇨🇴',
  'Colômbia': '🇨🇴',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Uruguai': '🇺🇾',
  'Indonesia': '🇮🇩',
  'Indonésia': '🇮🇩',
  'Turquia': '🇹🇷',
  'Grecia': '🇬🇷',
  'Grécia': '🇬🇷',
  'Espanha': '🇪🇸',
  'Finlandia': '🇫🇮',
  'Finlândia': '🇫🇮',
  'Dinamarca': '🇩🇰',
  'Austria': '🇦🇹',
  'Áustria': '🇦🇹',
  'Africa do Sul': '🇿🇦',
  'África do Sul': '🇿🇦',
  'Arabia Saudita': '🇸🇦',
  'Arábia Saudita': '🇸🇦',
  'Russia': '🇷🇺',
  'Rússia': '🇷🇺',
  'Internacional': '🌍',
  'Uniao Africana': '🌍',
  'União Africana': '🌍',
  'Uniao Europeia': '🇪🇺',
  'União Europeia': '🇪🇺',
  'Venezuela': '🇻🇪',
  'Equador': '🇪🇨',
  'Bolivia': '🇧🇴',
  'Bolívia': '🇧🇴',
  'Paraguai': '🇵🇾',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Panamá': '🇵🇦',
  'Guatemala': '🇬🇹',
  'Honduras': '🇭🇳',
  'El Salvador': '🇸🇻',
  'Nicaragua': '🇳🇮',
  'Nicarágua': '🇳🇮',
  'Rep. Dominicana': '🇩🇴',
  'Cuba': '🇨🇺',
  'Haiti': '🇭🇹',
  'Jamaica': '🇯🇲',
  'Trinidad e Tobago': '🇹🇹',
  'Barbados': '🇧🇧',
  'Bahamas': '🇧🇸',
  'Guiana': '🇬🇾',
  'Belize': '🇧🇿',
  'Bruxelas (Comissao Europeia)': '🇪🇺',
  'Bruxelas (Comissão Europeia)': '🇪🇺',
};

export function getFlag(pais) {
  if (!pais) return '🏳️';
  return countryFlags[pais] || '🏳️';
}

export default countryFlags;
